---
- name: Install filebeat
  become: true
  yum:
    name: "/tmp/filebeat-{{ elasticsearch_version }}-x86_64.rpm"
    state: present
  notify: restart filebeat
- name: Start service
  become: true
  systemd:
    name: filebeat
    state: started    
  notify: restart filebeat  
